tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#353534",
        "on-primary-fixed-variant": "#930000",
        "on-tertiary-fixed": "#1a1c1c",
        background: "#131313",
        secondary: "#fff9ef",
        "on-secondary": "#3a3000",
        "on-surface-variant": "#e4beba",
        "secondary-fixed-dim": "#e9c400",
        "on-primary-fixed": "#410000",
        "on-primary-container": "#fff2f0",
        outline: "#ab8985",
        "surface-tint": "#ffb4a8",
        "primary-container": "#dd180d",
        "surface-bright": "#393939",
        "surface-container-high": "#2a2a2a",
        "surface-container-low": "#1c1b1b",
        "on-primary": "#690000",
        "inverse-on-surface": "#313030",
        "surface-container-lowest": "#0e0e0e",
        "secondary-container": "#ffdb3c",
        "surface-variant": "#353534",
        tertiary: "#c6c6c6",
        "on-secondary-fixed": "#221b00",
        "inverse-primary": "#c00000",
        "tertiary-container": "#6f7070",
        "tertiary-fixed": "#e2e2e2",
        surface: "#131313",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a8",
        "on-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c6c6c6",
        "surface-container": "#201f1f",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#544600",
        "on-tertiary-container": "#f5f5f5",
        "on-secondary-container": "#725f00",
        "error-container": "#93000a",
        "on-tertiary": "#2f3131",
        error: "#ffb4ab",
        "secondary-fixed": "#ffe16d",
        "outline-variant": "#5b403d",
        "surface-dim": "#131313",
        "on-tertiary-fixed-variant": "#454747",
        primary: "#ffb4a8",
        "on-background": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        /* Amarillo cartelería del local (letreros H&H) */
        "hh-yellow": "#FBD80D",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
    },
  },
};
